### PR TITLE
unit test view

### PR DESCRIPTION
**Pull request by phuongha47**
## Related Tickets:
- [#45977](https://edu-redmine.sun-asterisk.vn/issues/45977)

## WHAT this PR does?
- Unit test View: UserListTest

## Notes Impacted Areas:
- N/A.

## Attachments:
- N/A.

### CODE REVIEW

**Comment by phuongha47** [comment]
ready

**Comment by Khoacannotcode** [comment]
Okay, LGTM 👏👏

**Comment by phuongha47** [comment]
ready

**Comment by phuongha47** [comment]
ready

**Comment by phuongha47** [comment]
ready

**Comment by manhtd-1083** [comment]
ready

**Comment by phuongha47** [comment]
ready

**Pull request merged**
