### PR TITLE
init project

### PR DESCRIPTION
**Pull request by Khoacannotcode**
- Install project based on Laravel 7
- Add makefile for automatically UI template setup
- Add PULL_REQUEST_TEMPLATE.md and .sun-ci.yml
- Modify .env.example

### CODE REVIEW

**Comment by Khoacannotcode** [comment]
ready

**Comment by Khoacannotcode** [comment]
ready

**Comment by Khoacannotcode** [comment]
ready

**Comment by Khoacannotcode** [comment]
ready

**Comment by manhtd-1083** [comment]
ready

**Pull request closed without merging**
